### ISSUE TITLE
Add support for SecRuleUpdateTargetById and SecRuleUpdateTargetByTag

### ISSUE THREAD

**Issue by azurit** [coreruleset/secrules_parsing#43]
Support for `SecRuleUpdateTargetById` is missing and that's why lint check is failing for new version of phpMyAdmin RE plugin:
https://github.com/coreruleset/phpmyadmin-rule-exclusions-plugin/actions/runs/4322401864/jobs/7544774067

The same applies for `SecRuleUpdateTargetByTag`.

**Comment by azurit** [comment]
The same problem is with `SecRuleUpdateTargetByTag`.

**Comment by Xhoenix** [comment]
I've opened a PR #46 for this.

**Comment by airween** [comment]
Closed via #46.
